### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by edoardohorse** [edoardohorse/ETADownloadFile#1]
- [ ] Need to implement more dimension (MB/KB) at more speed (Gbits/Kbits)
- [ ] Add countdown that tells how much time remain (decreasing)
- [ ] Add english language
